version: "3.9"

services:
  speedtestidbot:
    container_name: speedtestidbot
    image: speedtestidbot
    build: .
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    init: true
    env_file: .env
    restart: unless-stopped
