version: "3.9"

services:
  speedtestidbot:
    container_name: speedtestidbot
    build: .
    ports:
      - "8080:8080"
    image: speedtestidbot
    init: true
    env_file: .env
    restart: unless-stopped
